### PR TITLE
post self beaconing live deployment additions

### PR DESCRIPTION
**Pull request by andymck**
1.  dont include any self witness in the final 14 witness list, drop em to the the floor
2. refactor calc_fspl, account for beacon gain

### CODE REVIEW

**Comment by andymck** [comment]
this version will drop the self witnessing in such a way they will not show up in the selected or unselected lists.  It is likely preferable to get the self witnesses into the unselected lists.  I am still trying to work out an efficient way to do that ( ie no quadratic within a for loop ).  

There is the drain_filter method but that is experimental ?  @maplant @madninja any ideas here and thoughts on using experimental   APIs ?

**Comment by madninja** [comment]
> this version will drop the self witnessing in such a way they will not show up in the selected or unselected lists. It is likely preferable to get the self witnesses into the unselected lists. I am still trying to work out an efficient way to do that ( ie no quadratic within a for loop ).
> 
> There is the drain_filter method but that is experimental ? @maplant @madninja any ideas here and thoughts on using experimental APIs ?

Not a fan of experimental apis for production code

**Comment by andymck** [comment]
I think i am overthinking this.  Unless someone objects, I am going to stick with filtering the self witnesses out.  They wont make it to the selected or unselected lists.  This replicates the erlang behaviour where they will simply dropped to the floor

**Comment by madninja** [comment]
> I think i am overthinking this. Unless someone objects, I am going to stick with filtering the self witnesses out. They wont make it to the selected or unselected lists. This replicates the erlang behaviour where they are simply dropped to the floor

Fine.. I was hoping to be able to track them for any gaming angles and improving the client side.

**Pull request closed without merging**
