### PR TITLE
Allow specifying dotenv file path at CLI

### LINKED ISSUE #77: Add explicit `-f` to load dot env from explicit location
For operational purposes, it would be extremely useful to have a CLI mechanism to explicitly specify a location for a dotenv file to load at start up.

### PR DESCRIPTION
**Pull request by xandkar**
fixes #77

### CODE REVIEW

**Comment by madninja** [comment]
Ugh.. this won't quite be needed once we switch to the `config` based approach. Can we talk about this and have you adjust if I push up a sample for an upcoming oracle?

**Comment by xandkar** [comment]
> Ugh.. this won't quite be needed once we switch to the `config` based approach. Can we talk about this and have you adjust if I push up a sample for an upcoming oracle?

Of course. Pinging on Discord.

**Comment by madninja** [comment]
> > Ugh.. this won't quite be needed once we switch to the `config` based approach. Can we talk about this and have you adjust if I push up a sample for an upcoming oracle?
> 
> Of course. Pinging on Discord.

Note the use of `Settings` in main.rs with the add of `-c` to take the path to the config file

**Comment by xandkar** [comment]
Closing, since obsoleted by #142

**Pull request closed without merging**
