### PR TITLE
Clear orphan coverage objects

### PR DESCRIPTION
**Pull request by macpie**
If we run, it will delete:
- Last month = 45k
- Last week = 75K

Total current records 120k

Doing last period and keeping the last 10 valid should delete about 62k coverage objects.

### CODE REVIEW

**Comment by bbalser** [comment]
are you proposing that this function is run once a day as part of the cleanup process after rewards have been output?

**Comment by macpie** [comment]
> are you proposing that this function is run once a day as part of the cleanup process after rewards have been output?

I was looking at it more before making a decision but I think yes that would be the goal. We just need to decide if we want to remove month old or week old.

**Comment by macpie** [comment]
@thehardbits Could you confirm that any heartbeat that comes in should always have the latest coverage object uuid?

**Comment by thehardbits** [comment]
No, unfortunately that's not the case. Sometimes time radio misses the last CO and continues to send old.  But radio should not fallback to previously used CO in case it sends new one in HB messages.

**Review by bbalser — APPROVED** [review]

**Pull request merged**
